Watching for file changes with StatReloader
Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Bad Request: /
[30/May/2025 17:31:02] "GET / HTTP/1.1" 400 86996
Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[30/May/2025 17:31:03] "GET /favicon.ico HTTP/1.1" 400 86777
Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Bad Request: /
[30/May/2025 17:32:12] "GET / HTTP/1.1" 400 87130
Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[30/May/2025 17:32:13] "GET /favicon.ico HTTP/1.1" 400 86774
Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Bad Request: /
[30/May/2025 17:32:16] "GET / HTTP/1.1" 400 87130
Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[30/May/2025 17:32:17] "GET /favicon.ico HTTP/1.1" 400 86774
Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Bad Request: /
[30/May/2025 17:32:46] "GET / HTTP/1.1" 400 86993
Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[30/May/2025 17:32:48] "GET /favicon.ico HTTP/1.1" 400 86774
Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Bad Request: /
[30/May/2025 17:37:37] "GET / HTTP/1.1" 400 87130
Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[30/May/2025 17:37:38] "GET /favicon.ico HTTP/1.1" 400 86774
/workspace/Compta/ComptaFreelance/urls.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 30, 2025 - 17:30:46
Django version 5.2.1, using settings 'ComptaFreelance.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

WARNING: This is a development server. Do not use it in a production setting. Use a production WSGI or ASGI server instead.
For more information on production servers see: https://docs.djangoproject.com/en/5.2/howto/deployment/
Watching for file changes with StatReloader
Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Bad Request: /
[30/May/2025 17:39:11] "GET / HTTP/1.1" 400 87233
Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[30/May/2025 17:39:12] "GET /favicon.ico HTTP/1.1" 400 86774
Watching for file changes with StatReloader
Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Bad Request: /
[30/May/2025 17:44:31] "GET / HTTP/1.1" 400 87846
Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io'. You may need to add '8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[30/May/2025 17:44:33] "GET /favicon.ico HTTP/1.1" 400 87524
/workspace/Compta/ComptaFreelance/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 30, 2025 - 17:44:02
Django version 5.2.1, using settings 'ComptaFreelance.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

WARNING: This is a development server. Do not use it in a production setting. Use a production WSGI or ASGI server instead.
For more information on production servers see: https://docs.djangoproject.com/en/5.2/howto/deployment/
Watching for file changes with StatReloader
[30/May/2025 17:46:27] "GET / HTTP/1.1" 200 1951
Not Found: /favicon.ico
[30/May/2025 17:46:28] "GET /favicon.ico HTTP/1.1" 404 2505
[30/May/2025 17:46:37] "GET /admin/clients/client/add/ HTTP/1.1" 302 0
[30/May/2025 17:46:37] "GET /admin/login/?next=/admin/clients/client/add/ HTTP/1.1" 200 4211
[30/May/2025 17:46:38] "GET /static/admin/css/base.css HTTP/1.1" 200 22120
[30/May/2025 17:46:38] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
[30/May/2025 17:46:38] "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2808
[30/May/2025 17:46:38] "GET /static/admin/css/login.css HTTP/1.1" 200 951
[30/May/2025 17:46:38] "GET /static/admin/css/responsive.css HTTP/1.1" 200 16565
[30/May/2025 17:46:38] "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
[30/May/2025 17:46:38] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
Forbidden (Origin checking failed - https://8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io does not match any trusted origins.): /admin/login/
[30/May/2025 17:46:55] "POST /admin/login/?next=/admin/clients/client/add/ HTTP/1.1" 403 2590
Forbidden (Origin checking failed - https://8000-eudes8-compta-aciudv7blyb.ws-eu120.gitpod.io does not match any trusted origins.): /admin/login/
[30/May/2025 17:47:01] "POST /admin/login/?next=/admin/clients/client/add/ HTTP/1.1" 403 2590
/workspace/Compta/ComptaFreelance/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 30, 2025 - 17:45:58
Django version 5.2.1, using settings 'ComptaFreelance.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

WARNING: This is a development server. Do not use it in a production setting. Use a production WSGI or ASGI server instead.
For more information on production servers see: https://docs.djangoproject.com/en/5.2/howto/deployment/
Watching for file changes with StatReloader
[30/May/2025 17:48:30] "POST /admin/login/?next=/admin/clients/client/add/ HTTP/1.1" 302 0
[30/May/2025 17:48:31] "GET /admin/clients/client/add/ HTTP/1.1" 200 16104
[30/May/2025 17:48:31] "GET /static/admin/css/forms.css HTTP/1.1" 200 8525
[30/May/2025 17:48:31] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[30/May/2025 17:48:31] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
[30/May/2025 17:48:31] "GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
[30/May/2025 17:48:31] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
[30/May/2025 17:48:31] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
[30/May/2025 17:48:31] "GET /static/admin/js/core.js HTTP/1.1" 200 6208
[30/May/2025 17:48:31] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9777
[30/May/2025 17:48:31] "GET /static/admin/js/actions.js HTTP/1.1" 200 8076
[30/May/2025 17:48:31] "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
[30/May/2025 17:48:31] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
[30/May/2025 17:48:31] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
[30/May/2025 17:48:31] "GET /static/admin/css/widgets.css HTTP/1.1" 200 11991
[30/May/2025 17:48:31] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
[30/May/2025 17:48:32] "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
[30/May/2025 17:48:33] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[30/May/2025 17:48:33] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
[30/May/2025 17:50:00] "GET /static/admin/img/calendar-icons.svg HTTP/1.1" 200 2455
[30/May/2025 17:50:12] "POST /admin/clients/client/add/ HTTP/1.1" 302 0
[30/May/2025 17:50:12] "GET /admin/clients/client/ HTTP/1.1" 200 9776
[30/May/2025 17:50:12] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
[30/May/2025 17:50:12] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[30/May/2025 17:50:12] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[30/May/2025 17:50:12] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[30/May/2025 17:50:12] "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
[30/May/2025 17:50:12] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[30/May/2025 17:50:12] "GET /static/admin/js/theme.js HTTP/1.1" 304 0
[30/May/2025 17:50:13] "GET /static/admin/js/filters.js HTTP/1.1" 200 978
[30/May/2025 17:50:13] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[30/May/2025 17:50:13] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[30/May/2025 17:50:13] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[30/May/2025 17:50:22] "GET / HTTP/1.1" 200 2417
Not Found: /client/1/
[30/May/2025 17:50:25] "GET /client/1/ HTTP/1.1" 404 2499
/workspace/Compta/clients/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 30, 2025 - 17:48:04
Django version 5.2.1, using settings 'ComptaFreelance.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

WARNING: This is a development server. Do not use it in a production setting. Use a production WSGI or ASGI server instead.
For more information on production servers see: https://docs.djangoproject.com/en/5.2/howto/deployment/
Watching for file changes with StatReloader
/workspace/Compta/clients/urls.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 30, 2025 - 17:51:02
Django version 5.2.1, using settings 'ComptaFreelance.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

WARNING: This is a development server. Do not use it in a production setting. Use a production WSGI or ASGI server instead.
For more information on production servers see: https://docs.djangoproject.com/en/5.2/howto/deployment/
Watching for file changes with StatReloader
[30/May/2025 17:51:58] "GET /client/1/ HTTP/1.1" 200 2029
[30/May/2025 17:52:07] "GET / HTTP/1.1" 200 2417
[30/May/2025 17:52:09] "GET /client/1/ HTTP/1.1" 200 2029
[30/May/2025 17:55:16] "GET /client/1/ HTTP/1.1" 200 4527
[30/May/2025 17:58:13] "GET /client/1/ HTTP/1.1" 200 10130
[30/May/2025 18:02:07] "GET /client/1/ HTTP/1.1" 200 11003
[30/May/2025 18:02:54] "GET /client/1/ HTTP/1.1" 200 11003
[30/May/2025 18:05:22] "GET /client/1/ HTTP/1.1" 200 10149
/workspace/Compta/ComptaFreelance/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 30, 2025 - 17:51:18
Django version 5.2.1, using settings 'ComptaFreelance.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

WARNING: This is a development server. Do not use it in a production setting. Use a production WSGI or ASGI server instead.
For more information on production servers see: https://docs.djangoproject.com/en/5.2/howto/deployment/
Watching for file changes with StatReloader
[30/May/2025 18:12:15] "GET /client/1/ HTTP/1.1" 200 8928
[30/May/2025 18:12:16] "GET /static/css/style.css HTTP/1.1" 200 33884
Performing system checks...

System check identified no issues (0 silenced).
May 30, 2025 - 18:09:34
Django version 5.2.1, using settings 'ComptaFreelance.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

WARNING: This is a development server. Do not use it in a production setting. Use a production WSGI or ASGI server instead.
For more information on production servers see: https://docs.djangoproject.com/en/5.2/howto/deployment/
Watching for file changes with StatReloader
[30/May/2025 18:32:01] "GET / HTTP/1.1" 200 1855
[30/May/2025 18:32:01] "GET /static/css/style.css HTTP/1.1" 304 0
Not Found: /favicon.ico
[30/May/2025 18:32:02] "GET /favicon.ico HTTP/1.1" 404 2789
[30/May/2025 18:32:10] "GET /admin/clients/client/add/ HTTP/1.1" 200 16104
[30/May/2025 18:32:11] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[30/May/2025 18:32:11] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[30/May/2025 18:32:11] "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
[30/May/2025 18:32:11] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[30/May/2025 18:32:11] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[30/May/2025 18:32:11] "GET /static/admin/js/theme.js HTTP/1.1" 304 0
[30/May/2025 18:32:11] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[30/May/2025 18:32:11] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[30/May/2025 18:32:11] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[30/May/2025 18:32:11] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[30/May/2025 18:32:11] "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
[30/May/2025 18:32:11] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
[30/May/2025 18:32:11] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[30/May/2025 18:32:11] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[30/May/2025 18:32:11] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[30/May/2025 18:32:11] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[30/May/2025 18:32:11] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[30/May/2025 18:32:11] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
[30/May/2025 18:32:11] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[30/May/2025 18:32:11] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[30/May/2025 18:32:11] "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
[30/May/2025 18:32:11] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[30/May/2025 18:32:12] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
[30/May/2025 18:32:15] "GET /client/1/ HTTP/1.1" 200 8928
Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Bad Request: /clients/1/
[30/May/2025 18:40:26] "GET /clients/1/ HTTP/1.1" 400 81897
Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[30/May/2025 18:40:26] "GET /favicon.ico HTTP/1.1" 400 81722
/workspace/Compta/ComptaFreelance/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 30, 2025 - 18:31:35
Django version 5.2.1, using settings 'ComptaFreelance.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

WARNING: This is a development server. Do not use it in a production setting. Use a production WSGI or ASGI server instead.
For more information on production servers see: https://docs.djangoproject.com/en/5.2/howto/deployment/
Watching for file changes with StatReloader
Not Found: /clients/1/
[30/May/2025 18:41:12] "GET /clients/1/ HTTP/1.1" 404 2751
Not Found: /favicon.ico
[30/May/2025 18:41:12] "GET /favicon.ico HTTP/1.1" 404 2754
[30/May/2025 18:41:45] "GET /client/1/ HTTP/1.1" 200 9795
[30/May/2025 18:41:45] "GET /static/css/style.css HTTP/1.1" 200 34351
Not Found: /favicon.ico
[30/May/2025 18:41:45] "GET /favicon.ico HTTP/1.1" 404 2754
[30/May/2025 18:42:26] "GET /client/1/ HTTP/1.1" 200 9795
[30/May/2025 18:42:27] "GET /static/css/style.css HTTP/1.1" 200 34351
[30/May/2025 18:42:36] "GET /client/1/ HTTP/1.1" 200 9795
